### ISSUE TITLE
rest api port showing 404 error

### ISSUE THREAD

**Issue by hirunair** [malsadi87/sawtooth-tuna#1]
The docker is running and we referred to the .yaml file for the respective ports where the rest api port shows 404 error and the validator port shows "page isn't working local host entered invalid response". Is there anything we can do to solve this error?

![image](https://user-images.githubusercontent.com/8462792/162558470-83a045c2-cfa3-4270-bdd9-f043e242b220.png)

**Comment by nayan2** [comment]
The issue has been solved.
