### ISSUE TITLE
Compare the hashed on-chain data to the DB data

### ISSUE THREAD

**Issue by jakobsn** [malsadi87/sawtooth-tuna#10]
Collect the relevant data in the database, hash and compare it to the related on-chain hash to verify information.

**Comment by jakobsn** [comment]
@nayan2 , I suggest that you look into this one after doing issue 7.

**Comment by nayan2** [comment]
A new end point is added to TP controllers(ex: http://localhost:3001/api/v1/sawtooth/tp/trip/verify/3) to verify the hashed data with current Data. With will return true or false.
