### ISSUE TITLE
Environment configuration

### ISSUE THREAD

**Issue by jakobsn** [malsadi87/sawtooth-tuna#14]
The environment configuration does not consider the production environment. E.g., the service is hosted on 16.170.7.117, but the environment.js is still:

export const environment = {
    production: false,
    endPointUrl: 'http://localhost:3001/api/v1',
    cacheTimeInMinute: 1,
    fakeBackEnd: false,
    enableAuth: true
}

<img width="1200" alt="Screenshot 2022-10-31 at 11 55 22" src="https://user-images.githubusercontent.com/9268039/198992324-a99f87d2-b3cf-44d4-b55c-b583b38f3944.png">

**Comment by jakobsn** [comment]
This also goes for the backend configuration main.ts. 

    app.enableCors({ origin: ['http://localhost:3000'] });

<img width="1558" alt="Screenshot 2022-10-31 at 12 02 20" src="https://user-images.githubusercontent.com/9268039/198993553-904b653a-4c33-4055-a761-db728b3065d4.png">

**Comment by nayan2** [comment]
I will fix the configuration, problem

**Comment by jakobsn** [comment]
Okay, I manually changed the values for the running instance for now.

**Comment by nayan2** [comment]
@jakobsn Do you mean that the application is not considering the environment.prod.js file?

**Comment by nayan2** [comment]
The issue has been fixed in both the Client and Backend. Changes in the NODE_ENV will change the configuration
