### ISSUE TITLE
Sign up and log in

### ISSUE THREAD

**Issue by jakobsn** [malsadi87/sawtooth-tuna#15]
The sign up page does not provide any user feedback when something goes wrong. For instance:
- Attempt to use an invalid email
- Use an already taken email
- Use a too short password or username
- Passwords don't match
- Don't press the "[ ]I agree all statements in [Terms of service](http://16.170.7.117:3000/auth/signup#!)" (not sure what the purpose of that button is)

Additionally, the application often freezes when failing at any of the above requirements and must be reloaded.

More advanced features we want?:
- Email verification
- Password reset

There is an option for social media login, but it is probably unnecessary at this time and can be removed or at least hidden.

**Comment by nayan2** [comment]
Created a new issue for reset passwords and email verification. So closing this issue
