### ISSUE TITLE
Email confirmation resend

### ISSUE THREAD

**Issue by jakobsn** [malsadi87/sawtooth-tuna#26]
If you fail to open the link for email verification, then the user will be stored and you'll never be able to send a confirmation email again.

**Comment by jakobsn** [comment]
Also, if you press the confirmation link again after already confirming the app will crash.

**Comment by nayan2** [comment]
Has been fixed both resend functionality(added) and retry URL problem(fixed) solved. One could find them in the new Repo main branch
