### ISSUE TITLE
Put credentials and keys in one environment file

### ISSUE THREAD

**Issue by jakobsn** [malsadi87/sawtooth-tuna#30]
I want one single environment file to insert all credentials, such as:

Postgres database username
Postgres database password

tunachain-db-admin username
tunachain-db-admin password

Smtp username
Smtp password
AWS_SES_ACCESS_KEY
AWS_SES_KEY_SECRET

JWT_SECRET
JWT_SECONDARY_TOKEN_SECRET

**Comment by nayan2** [comment]
Implemented in the main branch of the [REPO](https://github.com/paasforchain/paas4chain) given repo.
