### ISSUE TITLE
Data validation(API): The location, tilt, shock and temperature variables in palletEvents

### ISSUE THREAD

**Issue by jakobsn** [malsadi87/sawtooth-tuna#7]
The location, tilt, shock and temperature variables in palletEvents should be validated objects based on the expected data:

- Temperature: double
- Tilt: JSON {x=double, y=double}
- Shock: JSON {acceleration=double, y=duration}
- Location:  JSON {latitude=double, longitude=double}

Current input data are arbitrary JSON objects.

**Comment by jakobsn** [comment]
After meeting with sintef today we were told that the temperature should not be JSON but only a simple double variable. Should not need much validation other than changing the data type.

**Comment by nayan2** [comment]
@jakobsn, Seems like the problem is related to validation, not storing the data. So, rather than changing the data type from JSON to any other type, I added validation. Which will validation the data, and send it through the API.
